name: "jest-github-action"
description: "Jest action adding checks to your pull requests"
inputs:
  github-token:
    description: "Your Github token"
    required: true
  test-command:
    description: "The test command to run"
    required: false
    default: "npm test"
outputs:
  time: # output will be available to future steps
    description: "The message to output"
runs:
  using: "node12"
  main: "dist/index.js"
