name: "jest-github-action"
description: "Jest action adding checks to your pull requests"
inputs:
  github-token:
    description: "Your Github token"
    required: true
  test-command:
    description: "The test command to run"
    required: false
    default: "npm test"
  coverage-comment:
    description: "Comment PRs with code coverage"
    required: false
    default: "true"

runs:
  using: "node12"
  main: "lib/run.js"
