name: "jest-github-action"
description: "Jest action adding checks to your pull requests"
inputs:
  test-command:
    description: "The test command to run"
    required: false
    default: "npm test"
  coverage-comment:
    description: "Comment PRs with code coverage"
    required: false
    default: "true"
  changes-only:
    description: "Only run tests on changed files (over base branch)"
    required: false
    default: "false"

runs:
  using: "node12"
  main: "dist/index.js"
